# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Niello"
license = "MIT"
licenselink = "https://github.com/guangmean/Niello/blob/master/LICENSE"
description = "A clean and elegant dark Theme for Hugo"
homepage = "https://github.com/guangmean/Niello"
demosite = "https://www.angularcorp.com"
tags = ["dark", "blog", "responsive", "modern", "minimal", "personal", "clean", "classic", "dark mode"]
features = ["google analytics", "google adsense", "search", "highlight", "i18n", "multiple language", "social media", "disqus", "tailwind"]
min_version = "0.100.0"

[author]
  name = "guangmean"
  homepage = "https://github.com/guangmean/Niello"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[module]
  [module.hugoVersion]
    min = "0.100.0"
    max = "0.136.2"
