baseURL = "https://www.example.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disqusShortname = "guangmean"   # Optional

staticDir = ["static", "themes/Niello/static"]

theme = "Niello"

[languages]
	[languages.en]
		languageCode = "en-us"
		LanguageName = "ðŸ‡ºðŸ‡¸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'exampleHome'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'exampleCategories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'exampleTags'
			pageRef = '/tags'
			weight = 3
	[languages.zh]
        languageCode = "zh-cn"
        LanguageName = "ðŸ‡¨ðŸ‡³CN"
        contentDir = "content/zh"
        weight = 2
		[[languages.zh.menus.main]]
			name = 'exampleé¦–é¡µ'
			pageRef = '/'
			weight = 1
		[[languages.zh.menus.main]]
			name = 'exampleæ–‡ç« åˆ†ç±»'
			pageRef = '/categories'
			weight = 2
		[[languages.zh.menus.main]]
			name = 'exampleæ ‡ç­¾'
			pageRef = '/tags'
			weight = 3

[params]
[params.google]
	google_ad_client = "******"
	ga4 = "******"
[params.bannershowcase]
	categories = ["Example 1 - EN"]
	limit = 2
[params.email]
	contact = "example@gmail.com"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie"]

copyright = "&#xA9; 2019 ~ 2024 by www.example.com All Rights Reserved."
sharethis = "******"

[outputs]
  home = ["HTML", "JSON"]   # Optional - JSON just for search